audit_header: false
title: Orange Countys Best Real Estate Training
description: Robert Mack, a top Real Estate Agent in Irvine, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Free Strategy Call
    url: /contact/
client:
  name: Robert Mack
  title:
  license_number: 'CA BRE# 01734565'
  about_markdown: |
    I’ve been a realtor for 13 years. I spent the first 7 years of my real estate career just trying to figure this business out. Made mistakes, learned from them, and constantly looking for ways to perfect my craft, be different, and be better. I had no mentor or guidance, I just had to figure it out on my own. Now I’m among the top 5% of realtors in the country. In addition to serving my clients at the highest level, I’ve now become a team leader and one of my passions is to mentor and guide newer agents to be more successful in less time by helping them learn more through all the mistakes I made! If you are a new or solo agent struggling to create a consistent business model, and you’re looking to be a part of something bigger, I would love the opportunity to have a strategy session with you to see if you would be the right fit for the Robert Mack Group! Real estate has many moving parts, and my goal is to create a team of agents who thrive at the highest level but also have a life worth living.
  market: Orange County
  brand: Robert Mack Group
  brokerage: Keller Williams
  address: 4010 barranca Park Way, Suite 100 Irvine, CA 92604
  phone: 949-209-7309
  phone_type:
  phone2:
  phone2_type:
  email: robertm@robertmackgroup.com
  url: https://www.robertmackgroup.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Robert Mack Group can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: falseo
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Why-Robert-Mack-Strategies-for-Real-Estate-Agents-700218823744619/?modal=admin_todo_tour
  linkedin_url:
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCF2Ts9NKEQOVi2yPY5fpCOQ
  twitter_url: https://twitter.com/robertmack
  instagram_url: http://instagram.com/robertmackgroup
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Irvine Real Estate Podcast with Robert Mack'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Irvine Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Robert Mack Group - your professional Irvine Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Irvine, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Robert Mack'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Irvine Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#999'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#999'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
